<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Ecommerce.Cart.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Cart.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cart.Application\Cart.Application.csproj" />
    <ProjectReference Include="..\Cart.Infrastructure\Cart.Infrastructure.csproj" />
  </ItemGroup>

</Project>
